apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-site-deployment
  labels:
    app: my-site
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-site
  template:
    metadata:
      labels:
        app: my-site
    spec:
      containers:
        - name: my-site
          image: localhost:5000/my-site:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-site-service
spec:
  selector:
    app: my-site
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer