apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-site-deployment
  labels:
    app: my-site
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-site
  template:
    metadata:
      labels:
        app: my-site
      annotations:
        redeploy-timestamp: "0"  # This will be overwritten to trigger redeploy
    spec:
      containers:
        - name: my-site
          image: localhost:5000/miniproject:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-site-service
spec:
  selector:
    app: my-site
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080